package sngular.com.atmsmap.app.constant;

public enum ATM_Type {
    ATM_SAME_ENTITY, ATM_SAME_GROUP_WITH_COMMISSION, ATM_SAME_GROUP_WITHOUT_COMMISSION, ATM_DIFFERENT_GROUP_WITH_COMMISSION,
        ATM_DIFFERENT_GROUP_WITHOUT_COMMISSION
}
